"""
build_all_erag_qrels.py

Given a <dataset>_all_runs.csv file (query_id, doc_id), compute the “model-based” eRAG qrels
for ALL (query_id, doc_id) pairs present, using a FiD-T5 model.

Default experiment layout
-------------------------
By default, this script assumes an experiment folder structure:

  <exp_root>/<dataset>/
    all-runs/        <dataset>_all_runs.csv
    all-qrels/       <dataset>_all_qrels.csv
    assessed-runs/   *_assessed_run.csv

Output
------
Writes <dataset>_all_qrels.csv with header:
  query_id, doc_id, relevance

and includes ONLY rows with relevance > 0.

Cache / incremental
-------------------
To avoid evaluating the same (query_id, doc_id) pair twice, it uses as cache:

1) Any <dataset>_all_qrels.csv file already present in the all-qrels folder
   (contains only relevance > 0).

2) Any *_assessed_run.csv files present in the assessed-runs folder (generated by
   build_all_assessed_runs.py), which also contain relevance = 0.

The “assessed_run” cache makes it possible to avoid recomputing even pairs already evaluated
with relevance = 0 (which do not appear in <dataset>_all_qrels.csv).

Note
----
Here we do NOT compute IR metrics (P@k, nDCG, etc.): we just need to generate the answer using
only that document as context and compute the downstream_metric (EM/Accuracy/F1),
which corresponds to the relevance to log.

Required inputs
---------------
- --all_runs: CSV with columns query_id, doc_id (any extra columns are ignored)
- --datasets: one or more KILT .jsonl files (for query_text and gold answers)
- --collection: JSONL document collection (id, contents)
- --model_dir: FiD-T5 model directory

CLI usage
-------
python build_all_erag_qrels.py \
  --exp_root ../exp-output \
  --dataset nq \
  --datasets ../data/nq-dev-kilt.jsonl \
  --collection ../data/collection/wikipedia_passages.jsonl \
  --model_dir ../models/fid_t5 \
  --metric em \
  --overwrite

Custom all_runs / output:
python build_all_erag_qrels.py \
  --all_runs ../exp-output/nq/all-runs/nq_all_runs.csv \
  --output  ../exp-output/nq/all-qrels/nq_all_qrels.csv \
  --datasets ../data/nq-dev-kilt.jsonl \
  --collection ../data/collection/wikipedia_passages.jsonl \
  --model_dir ../models/fid_t5 \
  --metric em \
  --overwrite
"""

from __future__ import annotations

import os
import json
import csv
import argparse
from typing import Dict, List, Tuple, Optional, Set, Any
from functools import partial
from collections import Counter

import torch
from transformers import T5Tokenizer, T5ForConditionalGeneration

from fid_t5 import t5_fid_generator
from metrics import exact_match_metric, f1_metric


# -----------------------------
# Downstream metrics (as in build_erag_qrels.py)
# -----------------------------
METRICS = {
    "em": exact_match_metric,
    "f1": f1_metric,
    "accuracy": exact_match_metric,  # in the project it coincides with EM
}


# -----------------------------
# Experiment paths
# -----------------------------
def default_exp_root() -> str:
    """
    Default exp-output root, relative to repository layout:
      repo_root/exp-output
    where repo_root is the parent directory of this src file.
    """
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    return os.path.join(repo_root, "exp-output")


def dataset_dir(exp_root: str, dataset: str) -> str:
    return os.path.join(exp_root, dataset)


def all_runs_default_path(exp_root: str, dataset: str) -> str:
    return os.path.join(dataset_dir(exp_root, dataset), "all-runs", f"{dataset}_all_runs.csv")


def all_qrels_default_path(exp_root: str, dataset: str) -> str:
    return os.path.join(dataset_dir(exp_root, dataset), "all-qrels", f"{dataset}_all_qrels.csv")


def assessed_runs_default_dir(exp_root: str, dataset: str) -> str:
    return os.path.join(dataset_dir(exp_root, dataset), "assessed-runs")


# -----------------------------
# Load all_runs (query_id, doc_id)
# -----------------------------
def load_all_runs_grouped(all_runs_path: str) -> Tuple[Dict[str, List[str]], Set[str], Set[str]]:
    """
    Load a <dataset>_all_runs.csv CSV and return:
      - pairs_by_qid: {query_id: [doc_id1, doc_id2, ...]} (dedup per query_id, appearance order)
      - qids: set(query_id)
      - docids: set(doc_id)

    Note: there is no score, so the order is not a ranking; it's only a processing order.
    """
    if not os.path.exists(all_runs_path):
        raise FileNotFoundError(f"all_runs not found: {all_runs_path}")

    pairs_by_qid: Dict[str, List[str]] = {}
    qids: Set[str] = set()
    docids: Set[str] = set()

    # dedup per qid preserving order
    seen_per_qid: Dict[str, Set[str]] = {}

    with open(all_runs_path, "r", encoding="utf-8", newline="") as f:
        r = csv.DictReader(f)
        for row in r:
            qid = str(row.get("query_id", "")).strip()
            did = str(row.get("doc_id", "")).strip()
            if not qid or not did:
                continue

            qids.add(qid)
            docids.add(did)

            if qid not in pairs_by_qid:
                pairs_by_qid[qid] = []
                seen_per_qid[qid] = set()

            if did in seen_per_qid[qid]:
                continue
            seen_per_qid[qid].add(did)
            pairs_by_qid[qid].append(did)

    return pairs_by_qid, qids, docids


# -----------------------------
# KILT dataset loading (only qids in the run)
# -----------------------------
def load_kilt_maps_for_qids(
    datasets: List[str],
    needed_qids: Set[str],
    *,
    max_examples: Optional[int] = None,
    prefix_with_dataset: bool = True,
) -> Tuple[Dict[str, str], Dict[str, List[str]]]:
    """
    Returns:
      query_id_to_query: {qid: query_text}
      expected_outputs:  {qid: [gold_answer1, ...]}
    """
    if not datasets:
        raise ValueError("No datasets provided.")

    multi = len(datasets) > 1
    qid2query: Dict[str, str] = {}
    qid2golds: Dict[str, List[str]] = {}
    remaining = set(needed_qids)

    for p in datasets:
        if not os.path.exists(p):
            raise FileNotFoundError(f"Dataset not found: {p}")

        prefix = None
        if prefix_with_dataset and multi:
            prefix = os.path.splitext(os.path.basename(p))[0]

        with open(p, "r", encoding="utf-8") as f:
            for i, line in enumerate(f):
                if max_examples is not None and i >= max_examples:
                    break
                line = line.strip()
                if not line:
                    continue

                try:
                    rec = json.loads(line)
                except Exception:
                    continue

                raw_qid = str(rec.get("id", i))
                qid = f"{prefix}:{raw_qid}" if prefix else raw_qid
                if qid not in remaining:
                    continue

                query_text = (rec.get("input") or "").strip()

                outputs = rec.get("output") or []
                golds: List[str] = []
                if isinstance(outputs, list):
                    for out in outputs:
                        ans = (out or {}).get("answer", None)
                        if isinstance(ans, str) and ans.strip():
                            golds.append(ans.strip())

                qid2query[qid] = query_text
                qid2golds[qid] = golds
                remaining.discard(qid)

                if not remaining:
                    break

        if not remaining:
            break

    return qid2query, qid2golds


# -----------------------------
# Collection loading (only docids in the run)
# -----------------------------
def _all_numeric_docids(docids: Set[str]) -> bool:
    return bool(docids) and all(str(d).isdigit() for d in docids)


def load_collection_contents_by_id_scan(collection_path: str, needed_docids: Set[str]) -> Dict[str, str]:
    """
    Streaming JSONL scan: match on the "id" field (doc_id string like 40885965_20).
    """
    doc_map: Dict[str, str] = {}
    remaining = set(needed_docids)

    with open(collection_path, "r", encoding="utf-8") as f:
        for line in f:
            if not remaining:
                break
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except Exception:
                continue

            did = str(rec.get("id", "")).strip()
            if not did or did not in remaining:
                continue

            contents = rec.get("contents") or rec.get("text") or ""
            doc_map[did] = contents
            remaining.discard(did)

    return doc_map


def load_collection_contents_by_line_offsets(
    collection_path: str,
    offsets_path: str,
    needed_docids: Set[str],
) -> Dict[str, str]:
    """
    Random-access lookup for numeric doc_id (line number) using uint64 offsets.
    """
    import mmap
    import struct

    ids = sorted({int(d) for d in needed_docids})
    doc_map: Dict[str, str] = {}

    with open(offsets_path, "rb") as off_f, open(collection_path, "rb") as col_f:
        mm = mmap.mmap(off_f.fileno(), 0, access=mmap.ACCESS_READ)
        count = len(mm) // 8

        def offset_at(i: int) -> int:
            return struct.unpack_from("<Q", mm, i * 8)[0]

        for i in ids:
            if i < 0 or i >= count:
                continue
            col_f.seek(offset_at(i))
            line = col_f.readline()
            try:
                rec = json.loads(line.decode("utf-8"))
            except Exception:
                continue
            contents = rec.get("contents") or rec.get("text") or ""
            doc_map[str(i)] = contents

        mm.close()

    return doc_map


def load_collection_contents_by_line_scan(collection_path: str, needed_docids: Set[str]) -> Dict[str, str]:
    """
    Slow fallback: scan and capture only the requested lines (numeric doc_id = line number).
    """
    needed_idx = {int(d) for d in needed_docids if str(d).isdigit()}
    doc_map: Dict[str, str] = {}

    with open(collection_path, "r", encoding="utf-8") as f:
        for i, line in enumerate(f):
            if i not in needed_idx:
                continue
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except Exception:
                continue
            contents = rec.get("contents") or rec.get("text") or ""
            doc_map[str(i)] = contents
            if len(doc_map) >= len(needed_idx):
                break

    return doc_map


def load_doc_id_to_document(
    collection_path: str,
    needed_docids: Set[str],
    *,
    offsets_path: Optional[str] = None,
) -> Dict[str, str]:
    if not os.path.exists(collection_path):
        raise FileNotFoundError(f"Collection not found: {collection_path}")

    if _all_numeric_docids(needed_docids):
        if offsets_path:
            if not os.path.exists(offsets_path):
                raise FileNotFoundError(f"Offsets not found: {offsets_path}")
            return load_collection_contents_by_line_offsets(collection_path, offsets_path, needed_docids)
        return load_collection_contents_by_line_scan(collection_path, needed_docids)

    return load_collection_contents_by_id_scan(collection_path, needed_docids)


# -----------------------------
# Cache loading: qrels + assessed runs
# -----------------------------
def _parse_relevance(raw_rel: Any) -> Any:
    """
    Robust parsing:
    - float(raw_rel) if possible
    - if nearly integer -> int (codebase style)
    - fallback 0
    """
    try:
        rel_val: Any = float(raw_rel)
        if abs(rel_val - round(rel_val)) < 1e-12:
            rel_val = int(round(rel_val))
        return rel_val
    except Exception:
        return 0


def list_assessed_run_files(folder: str) -> List[str]:
    files: List[str] = []
    if not os.path.isdir(folder):
        return files
    for name in os.listdir(folder):
        p = os.path.join(folder, name)
        if not os.path.isfile(p):
            continue
        if name.lower().endswith("_assessed_run.csv"):
            files.append(p)
    return sorted(files)


def load_positive_qrels_map(qrels_path: str) -> Dict[Tuple[str, str], Any]:
    """
    Load an existing <dataset>_all_qrels.csv and return:
      (query_id, doc_id) -> relevance

    Note: we expect only relevance > 0, but we do robust parsing and keep max on duplicates.
    """
    rel_map: Dict[Tuple[str, str], Any] = {}

    with open(qrels_path, "r", encoding="utf-8", newline="") as f:
        r = csv.DictReader(f)
        for row in r:
            qid = str(row.get("query_id", "")).strip()
            did = str(row.get("doc_id", "")).strip()
            if not qid or not did:
                continue

            rel_val = _parse_relevance(row.get("relevance", 0))
            try:
                rel_f = float(rel_val)
            except Exception:
                rel_f = 0.0

            if rel_f <= 0.0:
                continue

            key = (qid, did)
            if key in rel_map:
                try:
                    prev = float(rel_map[key])
                    cur = float(rel_val)
                    rel_map[key] = rel_val if cur > prev else rel_map[key]
                except Exception:
                    rel_map[key] = rel_val
            else:
                rel_map[key] = rel_val

    return rel_map


def load_assessed_runs_cache(folder: str) -> Tuple[Set[Tuple[str, str]], Dict[Tuple[str, str], Any], int]:
    """
    Scan *_assessed_run.csv in folder and return:
      - evaluated_pairs: set((query_id, doc_id)) for ALL rows (includes relevance=0)
      - positive_rel_map: (qid,did)->relevance ONLY for relevance>0 (max on duplicates)
      - files_count
    """
    evaluated_pairs: Set[Tuple[str, str]] = set()
    positive_rel_map: Dict[Tuple[str, str], Any] = {}

    files = list_assessed_run_files(folder)
    for p in files:
        with open(p, "r", encoding="utf-8", newline="") as f:
            r = csv.DictReader(f)
            if not r.fieldnames:
                continue

            needed = {"query_id", "doc_id", "relevance"}
            if not needed.issubset(set(r.fieldnames)):
                continue

            for row in r:
                qid = str(row.get("query_id", "")).strip()
                did = str(row.get("doc_id", "")).strip()
                if not qid or not did:
                    continue

                key = (qid, did)
                evaluated_pairs.add(key)

                rel_val = _parse_relevance(row.get("relevance", 0))
                try:
                    rel_f = float(rel_val)
                except Exception:
                    rel_f = 0.0

                if rel_f <= 0.0:
                    continue

                if key in positive_rel_map:
                    try:
                        prev = float(positive_rel_map[key])
                        cur = float(rel_val)
                        positive_rel_map[key] = rel_val if cur > prev else positive_rel_map[key]
                    except Exception:
                        positive_rel_map[key] = rel_val
                else:
                    positive_rel_map[key] = rel_val

    return evaluated_pairs, positive_rel_map, len(files)


# -----------------------------
# Output helpers
# -----------------------------
def infer_dataset_name_from_all_runs_path(all_runs_path: str) -> str:
    base = os.path.splitext(os.path.basename(all_runs_path))[0]
    suffix = "_all_runs"
    if base.endswith(suffix):
        return base[: -len(suffix)]
    return base


def infer_dataset_name_from_all_qrels_path(all_qrels_path: str) -> str:
    base = os.path.splitext(os.path.basename(all_qrels_path))[0]
    suffix = "_all_qrels"
    if base.endswith(suffix):
        return base[: -len(suffix)]
    return base


def format_relevance(score: float, score_precision: int = 6) -> Any:
    """
    Format relevance as in build_erag_qrels.py:
    - int if it's “nearly integer” (EM/accuracy)
    - otherwise a formatted float
    """
    try:
        s = float(score)
    except Exception:
        s = 0.0

    if abs(s - round(s)) < 1e-12:
        return int(round(s))

    fmt = f"{{:.{int(score_precision)}f}}"
    return float(fmt.format(s))


# -----------------------------
# Core: compute and write qrels (only relevance > 0), reusing cache
# -----------------------------
def write_all_erag_qrels_csv(
    pairs_by_qid: Dict[str, List[str]],
    query_id_to_query: Dict[str, str],
    doc_id_to_document: Dict[str, str],
    expected_outputs: Dict[str, List[str]],
    text_generator,
    downstream_metric_func,
    out_path: str,
    *,
    score_precision: int = 6,
    evaluated_pairs: Optional[Set[Tuple[str, str]]] = None,
    cached_positive_rel_map: Optional[Dict[Tuple[str, str], Any]] = None,
) -> None:
    """
    Run generation+metrics for each (qid, docid) pair in pairs_by_qid,
    skipping pairs present in evaluated_pairs (cache) and writing:

    - all cached pairs with relevance > 0 (cached_positive_rel_map)
    - all new pairs with relevance > 0

    Note:
    - evaluated_pairs is used to avoid recomputing pairs already evaluated with relevance=0 as well.
    - cached_positive_rel_map is only used to immediately write already-known positives.
    """
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    tmp_path = out_path + ".tmp"

    evaluated_pairs = evaluated_pairs or set()
    cached_positive_rel_map = cached_positive_rel_map or {}

    qids = list(pairs_by_qid.keys())
    max_len = max((len(lst) for lst in pairs_by_qid.values()), default=0)

    with open(tmp_path, "w", encoding="utf-8", newline="") as f_out:
        w = csv.writer(f_out)
        w.writerow(["query_id", "doc_id", "relevance"])

        # 1) write cached positives first
        cached_written = 0
        for (qid, did), rel in cached_positive_rel_map.items():
            try:
                rel_f = float(rel)
            except Exception:
                rel_f = 0.0
            if rel_f <= 0.0:
                continue
            w.writerow([qid, did, format_relevance(rel_f, score_precision=score_precision)])
            cached_written += 1

        written_new = 0
        processed_new = 0

        for i in range(max_len):
            # items: (qid, qtext, doc_id, doc_text)
            items: List[Tuple[str, str, str, str]] = []
            for qid in qids:
                doc_ids = pairs_by_qid.get(qid, []) or []
                if i >= len(doc_ids):
                    continue

                doc_id = str(doc_ids[i])
                key = (qid, doc_id)

                # cache hit: skip compute (includes relevance=0 already evaluated)
                if key in evaluated_pairs:
                    continue

                if qid not in query_id_to_query:
                    raise KeyError(f"query_id_to_query missing query_id: {qid}")

                qtext = query_id_to_query[qid]
                dtext = doc_id_to_document.get(doc_id, "")

                items.append((qid, qtext, doc_id, dtext))

            if not items:
                continue

            # Batch only on unique query_text; duplicates -> one-by-one
            qtext_counts = Counter(qtext for (_qid, qtext, _did, _dtext) in items)

            batch_input: Dict[str, List[str]] = {}
            batch_expected: Dict[str, List[str]] = {}
            backmap: List[Tuple[str, str, str]] = []  # (qid, qtext, doc_id)
            dup_items: List[Tuple[str, str, str, str]] = []

            for qid, qtext, doc_id, doc_text in items:
                if qtext_counts[qtext] == 1:
                    batch_input[qtext] = [doc_text]
                    batch_expected[qtext] = expected_outputs.get(qid, []) or []
                    backmap.append((qid, qtext, doc_id))
                else:
                    dup_items.append((qid, qtext, doc_id, doc_text))

            # --- Batch part ---
            if batch_input:
                generated = text_generator(batch_input)
                if set(generated.keys()) != set(batch_input.keys()):
                    raise RuntimeError("The text_generator function did not return outputs for all given inputs.")

                scores = downstream_metric_func(generated, batch_expected)
                if set(scores.keys()) != set(generated.keys()):
                    raise RuntimeError(
                        "The downstream_metric function did not return evaluation scores for all given inputs."
                    )

                for qid, qtext, doc_id in backmap:
                    processed_new += 1
                    s = float(scores.get(qtext, 0.0))
                    if s > 0.0:
                        w.writerow([qid, doc_id, format_relevance(s, score_precision=score_precision)])
                        written_new += 1

            # --- Duplicate query_text in same batch: one-by-one ---
            for qid, qtext, doc_id, doc_text in dup_items:
                generated = text_generator({qtext: [doc_text]})
                if qtext not in generated:
                    raise RuntimeError("The text_generator function did not return outputs for all given inputs.")
                scores = downstream_metric_func(generated, {qtext: expected_outputs.get(qid, []) or []})
                if qtext not in scores:
                    raise RuntimeError(
                        "The downstream_metric function did not return evaluation scores for all given inputs."
                    )

                processed_new += 1
                s = float(scores.get(qtext, 0.0))
                if s > 0.0:
                    w.writerow([qid, doc_id, format_relevance(s, score_precision=score_precision)])
                    written_new += 1

            if (i + 1) % 10 == 0:
                print(
                    f"Processed rank-position i={i+1}/{max_len}. "
                    f"New pairs processed so far: {processed_new}, new written: {written_new}, cached written: {cached_written}"
                )

        print(
            f"Done. New pairs processed: {processed_new}, new written (relevance>0): {written_new}, "
            f"cached written: {cached_written}"
        )

    os.replace(tmp_path, out_path)
    print(f"Saved qrels -> {out_path}")


# -----------------------------
# Main
# -----------------------------
def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Build a single eRAG qrels CSV from <dataset>_all_runs.csv, keeping only relevance>0 pairs, "
            "reusing cache from existing <dataset>_all_qrels.csv and *_assessed_run.csv."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument(
        "--exp_root",
        type=str,
        default=default_exp_root(),
        help="Experiment output root folder containing <dataset>/all-runs, <dataset>/all-qrels, <dataset>/assessed-runs.",
    )
    parser.add_argument(
        "--dataset",
        type=str,
        default=None,
        help="Dataset name (e.g., nq). Used to build default paths under exp_root.",
    )

    parser.add_argument(
        "--all_runs",
        type=str,
        default=None,
        help="Path to <dataset>_all_runs.csv (query_id, doc_id). If not provided, it is inferred from exp_root and dataset.",
    )

    parser.add_argument("--datasets", type=str, nargs="+", required=True, help="KILT dataset(s) .jsonl")
    parser.add_argument("--max_examples", type=int, default=None, help="Limit examples per dataset (debug)")
    parser.add_argument(
        "--prefix_with_dataset",
        action="store_true",
        help="If multiple datasets, prefix query_id with dataset basename (must match all_runs).",
    )

    parser.add_argument("--collection", type=str, required=True, help="Collection JSONL with fields id, contents")
    parser.add_argument(
        "--offsets",
        type=str,
        default=None,
        help="Offsets uint64 for random access (only meaningful if doc_id are numeric line ids).",
    )

    parser.add_argument("--model_dir", type=str, required=True, help="FiD-T5 model directory")
    parser.add_argument("--max_input_len", type=int, default=256)
    parser.add_argument("--max_output_len", type=int, default=64)
    parser.add_argument("--num_beams", type=int, default=4)
    parser.add_argument("--batch_size", type=int, default=16, help="Batch size per generazione (raggruppando per #docs).")

    parser.add_argument("--metric", choices=list(METRICS.keys()), default="em")
    parser.add_argument("--score_precision", type=int, default=6)

    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Output CSV path. Default: <exp_root>/<dataset>/all-qrels/<dataset>_all_qrels.csv",
    )
    parser.add_argument("--overwrite", action="store_true")

    args = parser.parse_args()

    exp_root = os.path.abspath(args.exp_root)

    dataset_name: Optional[str] = args.dataset
    if dataset_name is None and args.all_runs:
        dataset_name = infer_dataset_name_from_all_runs_path(args.all_runs)

    if dataset_name is None and args.output:
        dataset_name = infer_dataset_name_from_all_qrels_path(args.output)

    if dataset_name is None:
        raise ValueError("dataset is required when --all_runs is not provided.")

    all_runs_path = args.all_runs or all_runs_default_path(exp_root, dataset_name)
    qrels_dir = os.path.dirname(all_qrels_default_path(exp_root, dataset_name))
    assessed_dir = assessed_runs_default_dir(exp_root, dataset_name)

    out_path = args.output or all_qrels_default_path(exp_root, dataset_name)
    output_dir = os.path.dirname(out_path) or "."
    os.makedirs(output_dir, exist_ok=True)

    if not os.path.exists(all_runs_path):
        raise FileNotFoundError(f"all_runs not found: {all_runs_path}")

    if os.path.exists(out_path) and not args.overwrite:
        raise FileExistsError(f"Output exists: {out_path} (use --overwrite)")

    downstream_metric_func = METRICS[args.metric]
    print(f"Downstream metric: {args.metric}")
    print(f"Dataset: {dataset_name}")
    print(f"exp_root: {exp_root}")
    print(f"all_runs: {all_runs_path}")
    print(f"qrels_dir: {qrels_dir}")
    print(f"assessed_dir: {assessed_dir}")

    # 1) load all_runs pairs
    pairs_by_qid, needed_qids_all, needed_docids_all = load_all_runs_grouped(all_runs_path)
    if not pairs_by_qid:
        raise RuntimeError("all_runs produced no rows.")
    n_pairs_all = sum(len(v) for v in pairs_by_qid.values())
    print(f"all_runs loaded: qids={len(needed_qids_all)}, unique_docids={len(needed_docids_all)}, total_pairs={n_pairs_all}")

    # 2) load caches
    evaluated_pairs: Set[Tuple[str, str]] = set()
    cached_positive_rel_map: Dict[Tuple[str, str], Any] = {}

    # 2.a) existing qrels cache (positives only)
    qrels_cache_candidates: List[str] = []
    standard_qrels_cache = os.path.join(qrels_dir, f"{dataset_name}_all_qrels.csv")
    if os.path.exists(standard_qrels_cache):
        qrels_cache_candidates.append(standard_qrels_cache)

    if os.path.exists(out_path) and os.path.abspath(out_path) != os.path.abspath(standard_qrels_cache):
        qrels_cache_candidates.append(out_path)

    loaded_qrels_pos = 0
    for qrels_cache_path in qrels_cache_candidates:
        qrels_pos = load_positive_qrels_map(qrels_cache_path)
        for k, rel in qrels_pos.items():
            if k in cached_positive_rel_map:
                try:
                    prev = float(cached_positive_rel_map[k])
                    cur = float(rel)
                    cached_positive_rel_map[k] = rel if cur > prev else cached_positive_rel_map[k]
                except Exception:
                    cached_positive_rel_map[k] = rel
            else:
                cached_positive_rel_map[k] = rel
        evaluated_pairs |= set(qrels_pos.keys())
        loaded_qrels_pos += len(qrels_pos)
        print(f"Loaded qrels cache: {qrels_cache_path} -> positives={len(qrels_pos)}")

    # 2.b) assessed_run caches (include zeros -> evaluated_pairs)
    assessed_cache_dirs: List[str] = []
    if os.path.isdir(assessed_dir):
        assessed_cache_dirs.append(assessed_dir)
    if os.path.isdir(output_dir) and os.path.abspath(output_dir) != os.path.abspath(assessed_dir):
        assessed_cache_dirs.append(output_dir)

    assessed_files_total = 0
    assessed_pairs_total: Set[Tuple[str, str]] = set()
    assessed_pos_total: Dict[Tuple[str, str], Any] = {}

    for d in assessed_cache_dirs:
        assessed_pairs, assessed_pos, assessed_files = load_assessed_runs_cache(d)
        assessed_files_total += assessed_files
        assessed_pairs_total |= assessed_pairs

        for k, rel in assessed_pos.items():
            if k in assessed_pos_total:
                try:
                    prev = float(assessed_pos_total[k])
                    cur = float(rel)
                    assessed_pos_total[k] = rel if cur > prev else assessed_pos_total[k]
                except Exception:
                    assessed_pos_total[k] = rel
            else:
                assessed_pos_total[k] = rel

        if assessed_files > 0:
            print(
                f"Loaded assessed_run cache: folder={d} -> files={assessed_files}, "
                f"evaluated_pairs={len(assessed_pairs)}, positives={len(assessed_pos)}"
            )

    if assessed_files_total > 0:
        evaluated_pairs |= assessed_pairs_total
        for k, rel in assessed_pos_total.items():
            if k in cached_positive_rel_map:
                try:
                    prev = float(cached_positive_rel_map[k])
                    cur = float(rel)
                    cached_positive_rel_map[k] = rel if cur > prev else cached_positive_rel_map[k]
                except Exception:
                    cached_positive_rel_map[k] = rel
            else:
                cached_positive_rel_map[k] = rel

    # 3) determine which pairs still need evaluation (cache miss)
    to_eval_qids: Set[str] = set()
    to_eval_docids: Set[str] = set()
    missing_pairs = 0

    for qid, doc_ids in pairs_by_qid.items():
        for did in doc_ids:
            key = (qid, str(did))
            if key in evaluated_pairs:
                continue
            missing_pairs += 1
            to_eval_qids.add(qid)
            to_eval_docids.add(str(did))

    print(f"Pairs to evaluate (cache miss): {missing_pairs} | cache hits: {n_pairs_all - missing_pairs}")

    # If nothing to compute, just write cached positives to output (header + relevance>0 rows)
    if missing_pairs == 0:
        print("Nothing to evaluate. Writing output from cache only.")
        write_all_erag_qrels_csv(
            pairs_by_qid={},  # no new compute
            query_id_to_query={},
            doc_id_to_document={},
            expected_outputs={},
            text_generator=lambda x: {},
            downstream_metric_func=lambda a, b: {},
            out_path=out_path,
            score_precision=args.score_precision,
            evaluated_pairs=evaluated_pairs,
            cached_positive_rel_map=cached_positive_rel_map,
        )
        return

    # 4) dataset -> query_id_to_query + expected_outputs (only qids to evaluate)
    query_id_to_query, expected_outputs = load_kilt_maps_for_qids(
        args.datasets,
        to_eval_qids,
        max_examples=args.max_examples,
        prefix_with_dataset=args.prefix_with_dataset,
    )
    missing_qids = sorted(list(to_eval_qids - set(query_id_to_query.keys())))
    if missing_qids:
        raise KeyError(f"{len(missing_qids)} query_id from all_runs not found in dataset(s). Examples: {missing_qids[:10]}")

    # 5) collection -> doc_id_to_document (only docids to evaluate)
    doc_id_to_document = load_doc_id_to_document(args.collection, to_eval_docids, offsets_path=args.offsets)
    missing_docids = sorted(list(to_eval_docids - set(doc_id_to_document.keys())))
    if missing_docids:
        print(
            f"WARNING: {len(missing_docids)} doc_id to evaluate not found in collection. "
            f"Examples: {missing_docids[:10]}. They will use empty contents."
        )
        for did in missing_docids:
            doc_id_to_document[did] = ""

    # 6) load model + generator
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Loading model: {args.model_dir} on {device}")
    model = T5ForConditionalGeneration.from_pretrained(args.model_dir)
    tokenizer = T5Tokenizer.from_pretrained(args.model_dir)
    model.to(device)
    model.eval()

    t5_generator = partial(
        t5_fid_generator,
        model=model,
        tokenizer=tokenizer,
        device=device,
        max_input_len=args.max_input_len,
        max_output_len=args.max_output_len,
        num_beams=args.num_beams,
        batch_size=args.batch_size,
    )

    # 7) compute relevance and write CSV (only >0), skipping cached evaluated pairs
    torch.cuda.empty_cache()
    write_all_erag_qrels_csv(
        pairs_by_qid=pairs_by_qid,
        query_id_to_query=query_id_to_query,
        doc_id_to_document=doc_id_to_document,
        expected_outputs=expected_outputs,
        text_generator=t5_generator,
        downstream_metric_func=downstream_metric_func,
        out_path=out_path,
        score_precision=args.score_precision,
        evaluated_pairs=evaluated_pairs,
        cached_positive_rel_map=cached_positive_rel_map,
    )


if __name__ == "__main__":
    main()